### ISSUE TITLE
In a fresh terminal, cdbk mis-remembers the named-directories if they contain spaces.

### ISSUE THREAD

**Issue by liamoc** [MikeDacre/cdbk#3]
Just to try it out, I made a music bookmark at the directory:

    /Users/liamoc/Music/iTunes/iTunes\ Media/Music

It worked at first, but if I restarted my terminal it suddenly had the `~music` bookmark pointing to the nonexistent directory:

    /Users/liamoc/Music/iTunes/iTunes

**Comment by MikeDacre** [comment]
Thanks for this @liamoc, I never explicitly considered names with spaces. The fix is to use quotation marks in the hash commands. I will push a commit now that will fix this, but you will need to explicitly fix your existing bookmarks. The best way to do this is to edit ~/.zshbookmarks and add quotation marks to the paths with spaces, e.g.:

```shell
hash -d music=/Users/liamoc/Music/iTunes/iTunes\ Media/Music
```

becomes:

```shell
hash -d music="/Users/liamoc/Music/iTunes/iTunes\ Media/Music"
```

Running `cdbk -r` can also fix this for you:

```shell
cdbk -r music /Users/liamoc/Music/iTunes/iTunes\ Media/Music
```

Thanks again

**Comment by liamoc** [comment]
Thanks for the fix!
